### ISSUE TITLE
Publish docker container to dockerhub

### ISSUE THREAD

**Issue by rickstaa** [paha/liquidctl-exporter#7]
@paha I believe publishing the docker image to DockerHub would enhance the user experience and streamline the documentation. This can be effortlessly executed through GitHub Actions (check out https://github.com/rickstaa/livepeer-exporter for a handy example).

**Comment by fma965** [comment]
This is a old comment, but pushing to GHCR is even easier. 

I've forked this and added a GHCR Package

```bash
docker run -d \
  --name liquidctl-exporter \
  --privileged \
  --network host \
  --restart unless-stopped \
  -p 9530:9530 \
  ghcr.io/fma965/liquidctl-exporter:latest
```

```yaml
services:
  liquidctl-exporter:
    image: ghcr,io/fma965/liquidctl-exporter
    container_name: liquidctl-exporter
    ports:
      - "9530:9530"
    privileged: true
    restart: unless-stopped
    network_mode: host
```
